### ISSUE TITLE
Support for advanced android completion, validation, .. inside XML android file

### ISSUE THREAD

**Issue by angelozerr** [Knowcode-AI/android-xml-editor#2]
I don't know if it is in the scope of your project, but I wonder if you would like to provide XML completion, validation
, and other features like color (ex : display a colored square after a color declaration), definition, etc inside XML editor and manage binding between XML and Java class (ex : having Java package completion for package attribute).

If you could interested you could manage that by developping a LemMinx extension for android, please read https://github.com/redhat-developer/vscode-xml/blob/master/docs/Extensions.md#custom-xml-extensions if you need some help, don't hesitate to post your question inside https://github.com/redhat-developer/vscode-xml/

**Comment by brunoamuniz** [comment]
Thanks for the suggestion

**Comment by angelozerr** [comment]
Thanks for your answer. You close the issue because you are not interested?

**Comment by brunoamuniz** [comment]
Hey @angelozerr sorry about that. We will consider it, for sure =)

Just closed it because it's not on our roadmap right now, but definitely it's in our backlog.

Cheers,

**Comment by angelozerr** [comment]
That's great, please ping me if you need some help. I think display a colored square after a color declaration could be nice but it will require to support in LemMinx side. Don't hesitate to ping me when you will have time to work on that.

**Comment by angelozerr** [comment]
For your information, you can now have a color support with vscode-xml:

![XMLSupportForAndroid](https://user-images.githubusercontent.com/1932211/211499060-00b9cda3-0b18-4100-a2d5-16b6be22eaba.png)

See https://github.com/redhat-developer/vscode-xml/blob/main/docs/Features/XMLColorsFeatures.md#define-color-in-text-content-with-colortext how to configure that.
